apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Values.name .Values.namespace}}
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/component: {{ printf "%s-%s" .Values.name .Values.namespace}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: http-grafana
    protocol: TCP
  selector:
    app: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/component: {{ printf "%s-%s" .Values.name .Values.namespace}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.name}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/app-root: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{.Values.virtualPath}}/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ printf "%s-%s" .Values.name .Values.namespace}}
            port:
              number: {{.Values.servicePort}}
