apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Values.name .Values.namespace}}
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/component: {{ printf "%s-%s" .Values.name .Values.namespace}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: http-grafana
    protocol: TCP
  selector:
    app: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.name .Values.namespace}}
    app.kubernetes.io/component: {{ printf "%s-%s" .Values.name .Values.namespace}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" .Values.name .Values.namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/app-root: /$1
spec:
  rules:
  - http:
      paths:
      - path: /{{.Values.sitePath}}/(.*)
        backend:
          serviceName: {{ printf "%s-%s" .Values.name .Values.namespace}}
          servicePort: {{.Values.servicePort}}
