apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app.kubernetes.io/name: {{.Values.name}}
    app.kubernetes.io/component: {{.Values.name}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}
    app.kubernetes.io/name: {{.Values.name}}
    app.kubernetes.io/component: {{.Values.name}}
---
# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: {{.Values.name}}
#  annotations:
#    ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: {{.Values.name}}
#            port:
#              number: {{.Values.servicePort}}
